#!/usr/bin/env python3
"""
Write the .xlsx fixtures the import tests read.

Hand-built rather than produced by a library, for the same reason the reader is
hand-written: the point of the test is that a real Excel container round-trips,
and a fixture generated by the same kind of tool that reads it would only prove
the two agree with each other.

The shapes here are the ones a supplier's file actually arrives in — a title
line above the header, blank rows in the middle, a 13-digit barcode stored as a
number, an accented product name, two sheets where only one is the price list,
and a cell whose text was edited in runs.

Run: python3 server/test/fixtures/make-xlsx.py
"""
import zipfile
from pathlib import Path

HERE = Path(__file__).parent


def esc(s):
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def col_name(i):
    name = ""
    i += 1
    while i:
        i, r = divmod(i - 1, 26)
        name = chr(65 + r) + name
    return name


def sheet_xml(rows, shared_index):
    """rows: list of list of (kind, value) where kind is 's' | 'n' | None."""
    out = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
        "<sheetData>",
    ]
    for r, row in enumerate(rows, start=1):
        if not any(cell is not None for cell in row):
            # A blank line is written self-closing, the way Excel writes it.
            out.append(f'<row r="{r}"/>')
            continue
        out.append(f'<row r="{r}">')
        for c, cell in enumerate(row):
            if cell is None:
                continue  # an empty cell is simply absent, as Excel writes it
            kind, value = cell
            ref = f"{col_name(c)}{r}"
            if kind == "s":
                out.append(f'<c r="{ref}" t="s"><v>{shared_index[value]}</v></c>')
            else:
                out.append(f'<c r="{ref}"><v>{value}</v></c>')
        out.append("</row>")
    out.append("</sheetData></worksheet>")
    return "".join(out)


def build(path, sheets, runs_cell=None):
    """sheets: list of (name, rows). runs_cell: a string stored as several runs."""
    strings = []
    index = {}
    for _, rows in sheets:
        for row in rows:
            for cell in row:
                if cell and cell[0] == "s" and cell[1] not in index:
                    index[cell[1]] = len(strings)
                    strings.append(cell[1])

    si = []
    for s in strings:
        if runs_cell is not None and s == runs_cell:
            # Split across runs, the way Excel stores part-formatted text.
            half = len(s) // 2
            si.append(
                f"<si><r><t>{esc(s[:half])}</t></r><r><t>{esc(s[half:])}</t></r></si>"
            )
        else:
            si.append(f'<si><t xml:space="preserve">{esc(s)}</t></si>')

    shared = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        f'count="{len(strings)}" uniqueCount="{len(strings)}">{"".join(si)}</sst>'
    )

    sheet_tags = "".join(
        f'<sheet name="{esc(name)}" sheetId="{i}" r:id="rId{i}"/>'
        for i, (name, _) in enumerate(sheets, start=1)
    )
    workbook = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        f"<sheets>{sheet_tags}</sheets></workbook>"
    )

    rel_tags = "".join(
        f'<Relationship Id="rId{i}" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
        f'Target="worksheets/sheet{i}.xml"/>'
        for i in range(1, len(sheets) + 1)
    )
    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        f"{rel_tags}</Relationships>"
    )

    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        "</Types>"
    )

    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", content_types)
        z.writestr("xl/workbook.xml", workbook)
        z.writestr("xl/_rels/workbook.xml.rels", rels)
        z.writestr("xl/sharedStrings.xml", shared)
        for i, (_, rows) in enumerate(sheets, start=1):
            z.writestr(f"xl/worksheets/sheet{i}.xml", sheet_xml(rows, index))


S = lambda v: ("s", v)  # noqa: E731
N = lambda v: ("n", v)  # noqa: E731

# A supplier's price list, with everything wrong with it that they always have.
catalogue = [
    [S("Al Rayan Trading — August price list")],  # a title above the header
    [],  # and a blank line
    [S("Item Name"), S("Code"), S("Retail"), S("Our Cost"), S("Qty"), S("Barcode"), S("Group")],
    [S("Braided USB-C cable"), S("CBL-01"), N(3.5), N(1.2), N(40), N(6291041500213), S("Accessories")],
    # A gap where a column simply has nothing in it — the classic way a
    # positional reader shifts every later value one to the left.
    [S("Café screen protector"), S("SCR-02"), N(8), None, N(25), N(6291041500220), S("Accessories")],
    [],  # a blank row in the middle of the data
    [S("Galaxy A15 128GB"), S("PH-A15"), N(189), N(150), N(4), N(8806095571584), S("Phones")],
]

notes = [
    [S("Delivery Tuesdays. Prices exclude VAT.")],
]

build(HERE / "supplier-catalogue.xlsx", [("Notes", notes), ("Price list", catalogue)],
      runs_cell="Braided USB-C cable")

print(f"wrote {HERE / 'supplier-catalogue.xlsx'}")

# An accounts export out of the shop's previous system.
#
# Shaped exactly like the real one this was written against: a chart of
# accounts rather than a list of people. The heading row sits above its
# members, one party is split into a pounds ledger and a dollars ledger, one
# account carries a balance with no name against it, one is in a currency this
# app does not keep, and one holds a figure left over from something that went
# wrong years ago.
accounts = [
    [S("Code"), S("Name"), S("Address"), S("Phone"), S("Balance"), S("Currency")],
    # A heading. It is a prefix of every code below it, which is how it is known.
    [S("401001"), S("Suppliers"), S(""), S(""), N(0), S("")],
    # An account with money against it and nobody's name.
    [S("401001000102"), S(""), S(""), S(""), N(129.97), S("USD")],
    # One supplier, two currency ledgers, one person.
    [S("401001000201"), S("I-PICK"), S(""), S(""), N(4291601000), S("LBP")],
    [S("401001000202"), S("I-PICK"), S(""), S("70001988"), N(-331.41), S("USD")],
    # The ordinary case: no currency ledger at all.
    [S("4010010003"), S("ALICELL"), S("Basta"), S("03158137"), N(0), S("")],
    [S("401001000402"), S("AHMAD HALABI"), S(""), S(""), N(-997), S("USD")],
    # Two suppliers with the same name and different codes: two suppliers.
    [S("401001000502"), S("CHINA"), S(""), S(""), N(-396.65), S("USD")],
    [S("401001000603"), S("CHINA"), S(""), S(""), N(-12621), S("¥")],
    # Five point eight trillion pounds, which is not a balance.
    [S("401001000701"), S("OMT Lira"), S(""), S(""), N(-5849985307864), S("LBP")],
]

build(HERE / "accounts-export.xlsx", [("Sheet1", accounts)])

print(f"wrote {HERE / 'accounts-export.xlsx'}")
